# ~/.bashrc

# Local binaries
export PATH="${PATH}:${HOME}/.local/bin"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#alias ls='ls --color=auto'
#PS1='[\u@\h \W]\$ '


# Default terminal
TERMINAL=xterm

export TERM=xterm-color

startx
