actions:
  pre:
    vim-plug-install: test -e ~/.vim/autoload/plug.vim || (mkdir -p ~/.vim/autoload;
      curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
  vim-plug: vim +PlugInstall +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_alacritty.yml:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_config:
    dst: ~/.config/i3/config
    src: config/i3/config
  f_config.rasi:
    dst: ~/.config/rofi/config.rasi
    src: config/rofi/config.rasi
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_entry.rasi:
    dst: ~/.config/rofi/entry.rasi
    src: config/rofi/entry.rasi
  f_i3status.conf:
    dst: ~/.config/i3/i3status.conf
    src: config/i3/i3status.conf
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_list.rasi:
    dst: ~/.config/rofi/list.rasi
    src: config/rofi/list.rasi
  f_termite_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_vimrc:
    actions:
    - vim-plug-install
    - vim-plug
    dst: ~/.vimrc
    src: vimrc
  f_xbindkeysrc:
    dst: ~/.xbindkeysrc
    src: xbindkeysrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xprofile:
    dst: ~/.xprofile
    src: xprofile
  f_zprofile:
    dst: ~/.zprofile
    src: zprofile
profiles:
  archlinux:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - f_config
    - f_i3status.conf
    - f_xbindkeysrc
    - f_zprofile
    - f_dunstrc
    - f_config.rasi
    - f_entry.rasi
    - f_list.rasi
    - f_compton.conf
    - f_termite_config
    - f_bashrc
    - f_bash_profile
    - f_alacritty.yml
    - f_init.vim
    - f_xprofile
